---
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles.repo }}"
    dest: "{{ dotfiles.repo_local_destination }}"
    recursive: yes
    update: yes
  become: false
  ignore_errors: yes

- name: Ensure all configured dotfiles are links.
  command: "ls -F {{ dotfiles.home }}/{{ item }}"
  register: existing_dotfile_info
  failed_when: false
  check_mode: false
  changed_when: false
  with_items: "{{ dotfiles.files }}"

- name: Remove existing dotfiles file if a replacement is being linked.
  file:
    path: "{{ dotfiles.home }}/{{ dotfiles.files[item.0] }}"
    state: absent
  when: "'@' not in item.1.stdout"
  with_indexed_items: "{{ existing_dotfile_info.results }}"

- name: Link dotfiles into home folder.
  file:
    src: "{{ dotfiles.repo_local_destination }}/{{ item }}"
    dest: "{{ dotfiles.home }}/{{ item }}"
    state: link
    mode: 0644
  become: false
  with_items: "{{ dotfiles.files }}"
