---
# Custom Terminal theme.
- name: Get current Terminal profile.
  shell: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: false

- name: Ensure custom Terminal profile is added.
  shell: open files/terminal/khiemns.terminal
  changed_when: false
  when: "'khiemns' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string khiemns
    - defaults write com.apple.terminal 'Startup Window Settings' -string khiemns
  changed_when: false
  when: "'khiemns' not in terminal_theme.stdout"
